### PR TITLE
Fix libc version detection if libcrypto is loaded

### PR DESCRIPTION
**Pull request by mephi42**
### Description/Motivation/Screenshots ###

I noticed that gef doesn't display tcache in some cases and tracked it
down to gef confusing libcrypto (which starts with "libc") with an
unknown libc. Fix by skipping unknown libcs.

Screenshot from 2021-01-11 12-44-48

### How Has This Been Tested? ###

| Architecture |          Yes/No          | Comments                                  |
| ------------ | :----------------------: | ----------------------------------------- |
| x86-32       | :heavy_multiplication_x: | Replace with :heavy_check_mark: if tested |
| x86-64       | :heavy_check_mark: |                                           |
| ARM          | :heavy_multiplication_x: |                                           |
| AARCH64      | :heavy_multiplication_x: |                                           |
| MIPS         | :heavy_multiplication_x: |                                           |
| POWERPC      | :heavy_multiplication_x: |                                           |
| SPARC        | :heavy_multiplication_x: |                                           |
| RISC-V       | :heavy_multiplication_x: |                                           |
| `make tests` | :heavy_multiplication_x: |                                           |

### Checklist ###

- [x] My PR was done against the `dev` branch, not `master`.
- [x] My code follows the code style of this project.
- [x] My change includes a change to the documentation, if required.
- [x] My change adds tests as appropriate.
- [x] I have read and agree to the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by Grazfather** [comment]
Good find, but I am not sure if the way you test is the best. Maybe we should use a regex e.g. `r"libc\W"`.

If you add an extra case in the end, make sure there's a comment explaining why.

**Comment by mephi42** [comment]
@Grazfather, this might still create problems with a hypothetical `my_awesome_libc_hooks.so`. I think it might be better to keep the patterns we are looking for, but restructure the code slightly. I've pushed the new version, what do you think about this approach?

@nola-milkin, since this touches the code you wrote recently, would you also mind reviewing this change? I did a test with a fake `libcqqq.so` shared library containing the string `glibc 1.2` and it worked, but maybe I still missed something.

**Comment by Grazfather** [comment]
Sorry! Missed this.

This looks pretty good to me. Thanks you for squashing. +1 from me, requesting review from @hugsy

**Review by Grazfather — APPROVED** [review]

**Review by hugsy — APPROVED** [review]

**Comment by Grazfather** [comment]
Thank you @mephi42

**Pull request merged**
