### PR TITLE
added ropper to dependencies

### PR DESCRIPTION
**Pull request by sashs**
I thought I add ropper to the dependencies in README :)

### CODE REVIEW

**Comment by hugsy** [comment]
I will accept the change, but before can you explain a bit in the README how `ropper` is different from `ROPgadget`. Some other people asked me to integrate their ROP tools and I didn't, so I wanna show why `ropper` was added :-) 

Thanks.

**Comment by sashs** [comment]
Sure, I will try to explain why you added it. ;-)

**Comment by hugsy** [comment]
:+1:

**Comment by sashs** [comment]
Done. :)

**Pull request merged**
