### PR TITLE
Minor improvements to stack displaying

### PR DESCRIPTION
**Pull request by etrickel-asu**
### Description ###

  - Added the option context.grow_stack_down, when enabled the stack will grow down, which pushes new items to bottom.
  - Added the option context.show_saved_ip, when enabled the context shows the saved ip and the ebp, it puts ... (XX btyes) between the frame pointer and where the stack display begins.
  - Changed stack alias and dereference function so that it would work with or without the L prefix in the input to dereference.
  - Added savedip label to regs array so that it'd be labeled when available
  - Added function get_saved_ip(), which uses the 'info frame' to find the saved instruction pointer address.

### Related Issue ###
None

### Motivation and Context ###
Thanks for all your work creating such a great tool!  I have been using the changes below in my own version of gef.  Since I have found them helpful, I thought others might as well, so I decided to share them.
Basically, I added 2 options for displaying stack info when using context and dereference function, which are disabled by default.  Changing the direction of the stack is useful for myself and others because we were taught and think about the stack as getting smaller as it goes down the screen.  The second improvement just includes the saved instruction pointer, base pointer, and a placeholder for the distance between the EBP and the top of the stack that is displayed.  

If you accept these changes, I'm hopeful they will bring about world peas.  

Thanks!
### How Has This Been Tested? ###

This patch has only been test on x86 platforms.  

| Architecture | Yes/No                   | Comments               |
|--------------|:------------------------:|------------------------|
| x86-32       | :heavy_check_mark:       |                        |
| x86-64       | :heavy_check_mark:       |                        |
| ARM          | :heavy_check_mark:       |                        |
| AARCH64      | :heavy_check_mark:       |                        |
| MIPS         | :heavy_check_mark:       |                        |
| POWERPC      | :heavy_check_mark:       |                        |
| SPARC        | :heavy_multiplication_x: | Who uses SPARC anyway? |

### Types of changes ###

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist ###

- [X ] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X ] I have read and agree to the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by etrickel-asu** [comment]
Sorry guys I made a mistake while trying to squash the commits.  Unfortunately, I removed the commit with the original pull request.  I tried to recover it, but github/git is not cooperating. :/

This should be the merged version with all the changes previously discussed.

**Comment by Grazfather** [comment]
Next time just use `git reflog` to find your commit before you made the mistake, and then do `git reset --hard HEAD@{<that number>}` to go back to the state before the squash.

This is fine, though.

**Comment by Grazfather** [comment]
The commits messages were a mess.

```bash
* ae72a11 2017-12-28 Some simple improvements to stack displaying in the dereference function geared towards X86 platforms - Added the option context.grow_stack_down, when enabled the stack will grow up on the display. - Added the option context.show_saved_ip, when enabled the context shows the saved ip and the ebp, it pu\    ts ... (XX btyes) between the base pointer and where the stack display begins.   * Both options are disabled by default. - Changed stack alias and dereference function so that it would work without requiring the L prefix. [etrickel]
```

I fixed them and pushed, so this is effectively merged.

**Comment by etrickel-asu** [comment]
Thanks for the tip, this is actually my first pull request, ever, so I 
really appreciate all your comments and help.

-Erik

**Comment by hugsy** [comment]
And thank you for contributing ! :+1:

**Comment by Grazfather** [comment]
Congratulations on your first PR :)

**Comment by hugsy** [comment]
Following up on this PR after doing some tests today, the "savedip" indicator doesn't work as intended when there is only frame.
Example from `master`:
```
$ gdb -ex start /bin/ls
```
c2oyimz

I will remove the PR from `master` and move it to `dev` for most tests (including non-x86 arch). I've also open an issue #205 to keep track.

@etrickel-asu Feel free to contribute.

**Pull request closed without merging**
