### PR TITLE
Fixed two occurrences of the typo "confortable" to "comfortable"

### PR DESCRIPTION
**Pull request by jordanallred**
## Description

-  [x] My code follows the code style of this project.
-  [x] My change includes a change to the documentation, if required.
-  [x] If my change adds new code, [adequate tests](docs/testing.md) have been added.
-  [x] I have read and agree to the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by hugsy** [comment]
Hi @jordanallred 

Thanks for the PR.
Can you remove the `gef.md` changes? That file is [generated automatically](https://github.com/hugsy/gef/blob/main/scripts/generate-api-docs.sh#L23) so your changes there won't be correctly applied.

**Comment by jordanallred** [comment]
> Hi @jordanallred
> 
> Thanks for the PR. Can you remove the `gef.md` changes? That file is [generated automatically](https://github.com/hugsy/gef/blob/main/scripts/generate-api-docs.sh#L23) so your changes there won't be correctly applied.

Done. Added a .gitignore that you can obviously delete as you see fit.

**Review by hugsy — CHANGES_REQUESTED** [review]
Just need to remove the empty line and we're good

**Comment by Grazfather** [comment]
This PR completely removes the md file?

**Comment by hugsy** [comment]
> This PR completely removes the md file?

Yes, do you think it's needed to be left in the repo since it's may be out of sync with the one generated automatically on merge to main?

**Comment by hugsy** [comment]
This PR still fails validation
image

**Pull request closed without merging**
