### PR TITLE
IndentationError: expected an indented block Fix

### PR DESCRIPTION
**Pull request by lillypad**
Fixes indentation error at line 4946 which prevents gdb from loading the .gdbinit-gef.py script.
Love the project I use this all the time, I'll buy you beer if we meet up someday.
Cheers!

##IndentationError: expected an indented block Fix ##

### Description ###
Fixes indentation error at line 4946 which prevents gdb from loading the .gdbinit-gef.py script.

### Related Issue ###

https://github.com/hugsy/gef/issues/XX

### Motivation and Context ###

Fixes indentation error currently script does not launch with gdb 7.x
GDB will be able to launch the .gdbinit-gef.py making life hella awesome duh.

### How Has This Been Tested? ###

Has this patch been tested on:
Linux d3d53c 4.4.39-gentoo #1 SMP Mon Jan 16 17:26:37 AST 2017 x86_64 Intel(R) Core(TM) i7-6560U CPU @ 2.20GHz GenuineIntel GNU/Linux

| Architecture | Yes/No                   | Comments               |
|--------------|:------------------------:|------------------------|
| x86-32       | :heavy_check_mark:       | rock'n roll            |
| x86-64       | :heavy_multiplication_x: |                        |
| ARM          | :heavy_check_mark:       |                        |
| AARCH64      | :heavy_multiplication_x: |                        |
| MIPS         | :heavy_check_mark:       |                        |
| POWERPC      | :heavy_check_mark:       |                        |
| SPARC        | :heavy_multiplication_x: | Who uses SPARC anyway? |

### Screenshots (if applicable) ###

image

### Types of changes ###

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist ###

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read and agree to the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by hugsy** [comment]
Thank you!

**Comment by hugsy** [comment]
Confirmed all is back to normal after this small glitch. 

Thank you @lillypad, you've [won yourself a beer](https://github.com/hugsy/gef#open-source-rewards) :beer: And really glad you appreciate `gef` and that you're contributing to it as well :smile: 

Cheers

**Comment by Grazfather** [comment]
My new PR fixes this. Looks like I fat fingered an edit: https://github.com/hugsy/gef/commit/e7f181cb039955d3ce2684de718facdda96a8b25#diff-c1353c3dea65fb78135f4781a0dddab0L4945

**Comment by hugsy** [comment]
@Grazfather yes I realized it and fixed it locally. Will push ASAP. Thanks

**Comment by lillypad** [comment]
Aww thanks hugsy winning a beer haha super stoked. :)

**Pull request merged**
