### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by aquynh**
Install Capstone as dependency (for Python3)

### CODE REVIEW

**Comment by hugsy** [comment]
Fixed by 566ec9392c34625d9aaf0ba8dd01d69638ccdf76
Thanks ;)

**Comment by aquynh** [comment]
Yes, it looks good now. But how about having the `pip install xxx` part to help users quickly install the dependencies, so that they do not need to spend time looking at the docs of other projects just to know how to install them?

Thanks.

**Comment by hugsy** [comment]
Ah ok, I see your point :+1: 
Done with 50686322c1986d6e426cde7c5457d1c7edc87fbc

**Comment by aquynh** [comment]
looks great now, thanks!

**Pull request closed without merging**
