### PR TITLE
Add get_cmd_output that calls a gdb cmd with no buffering

### LINKED ISSUE #362: bufferize makes gdb.execute(..., to_string=True) return nothing
if `gdb.execute(..., to_string=True)` is called while in a command invocation, then it will return an empty string if the invoked command buffers its output. This means it only affects using `gdb.execute` on our own commands, not builtins.

This is bad for commands that actually need its output.

I am surprised this isn't breaking more things. We might have to disable buffering (again) for the release.

### PR DESCRIPTION
**Pull request by Grazfather**
Fixes #362.

### CODE REVIEW

**Comment by Grazfather** [comment]
So this is only an issue if `gdb.execute` calls a GEF command, since built in obviously don't use `gef_print` and thus aren't bufferized.

**Comment by Grazfather** [comment]
@hugsy could you please test this with and without, using `ida_synchronize_handler`? It seems to be the only case where this would fail (all other invocations are builtins).

**Comment by hugsy** [comment]
Go for merge !

**Comment by Grazfather** [comment]
Were you able to validate that `ida_synchronize_handler` was broken without this?

**Comment by hugsy** [comment]
Yes my good sir !

capture

**Comment by Grazfather** [comment]
Going to close as unnecessary.

**Pull request closed without merging**
