### PR TITLE
Add Print Args functionality (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by Grazfather**
### Description ###
Arch specific:
* Add the ability to determine if the current instruction is a call.
* Add the ability to print out the guessed args

Generic:
* Add an option to the context command to print args when the PC points to one.
* For now it's default on and part of the layout.

### Related Issue ###
#56

### TODO ###
1. Other Architectures
  * AARCH64
  * MIPS
  * PPC
2. Make pretty
3. Instead of hardcoding a number of arguments, peek back and see what were set.

### CODE REVIEW

**Comment by Grazfather** [comment]
Have basic working for ARM:

**Comment by bennofs** [comment]
What's the state of this?

**Comment by Grazfather** [comment]
@bennofs I haven't worked on it in forever. It needs to be done manually for each ABI, and unfortunately it's extra tricky for x86 and x86_64. It also needs a rebase, though last I checked i think it was working for a few ABIs.

**Comment by Grazfather** [comment]
Rebased and merged what I have into the dev branch.

**Pull request closed without merging**
