### PR TITLE
fix gef_instruction_n off by one bug

### PR DESCRIPTION
**Pull request by thvdburgt**
### Description ###
gef_instruction_n returns the incorrect instruction for `n != 0`:

This is fixed with the first commit:

This also fixes `gef_next_instruction` which gave the current instruction back instead of the next one.
But this breaks the code context!

Looking into this it seems `gdb_disassemble` uses a different definition of `end_pc` as GDB.
I changed the documentation so it is in line with the GDB documentation.
`gdb_get_nth_previous_instruction_address` assumed the other behaviour which is why it broke when `gef_current_instruction` got fixed. This gets fixed in the other commits.

### Motivation and Context ###
gef_instruction_n returned the incorrect instruction for `n != 0`.

### How Has This Been Tested? ###
x86-64 and ARM

### Types of changes ###

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change) **(See next comment)**

### Checklist ###

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read and agree to the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by thvdburgt** [comment]
This lets `gef_disassemble` show one line more at the top, because `gdb_get_nth_previous_instruction_address` now returns the correct address. This should be an easy fix, but because I don't understand the need for
`count = nb_insn + 1 if nb_insn & 1 else nb_insn`
I didn't want to touch that function.

**Comment by hugsy** [comment]
The idea behind the line
```
count = nb_insn + 1 if nb_insn & 1 else nb_insn
```
was just for aesthetic to make sure that there is a same number of line above and under $pc.

@Grazfather : maybe this PR would be a good opportunity to integrate your suggestion #169 then ?

**Comment by hugsy** [comment]
@thvdburgt I am going to merge your PR. Can you squash it first?

Thanks.

**Comment by thvdburgt** [comment]
squashed

**Comment by hugsy** [comment]
Thanks man!

**Pull request merged**
