### PR TITLE
Support Safe-Linking in GlibC 2.32+

### PR DESCRIPTION
**Pull request by chkp-eyalit**
### Description/Motivation/Screenshots ###
glibc 2.32 will add support for protection of single-linked-lists such as the Fastbins and TCache lists. This support, which was [pushed](https://sourceware.org/git/?p=glibc.git;a=commit;h=a1a486d70ebcc47a686ff5846875eacad0940e41) already to glibc's master branch, is referred to us "Safe-Linking".

Safe-Linking masks the "fwd" pointers, and so this commit implements the support for unmasking ("reavel"ing) the pointers so they could be used properly by gef.

Note: Fixed my previous pull request so that the caller will explicitly pass True/False to specify if the "fwd" pointer is for a single-linked-list (SLL) or a double-linked-list which needs no unmasking.

### How Has This Been Tested? ###

| Architecture |          Yes/No          | Comments                                  |
| ------------ | :----------------------: | ----------------------------------------- |
| x86-32       | :heavy_check_mark: |                                               |
| x86-64       | :heavy_multiplication_x: |                                           |
| ARM          | :heavy_multiplication_x: |                                           |
| AARCH64      | :heavy_multiplication_x: |                                           |
| MIPS         | :heavy_multiplication_x: |                                           |
| POWERPC      | :heavy_multiplication_x: |                                           |
| SPARC        | :heavy_multiplication_x: |                                           |
| RISC-V       | :heavy_multiplication_x: |                                           |
| `make tests` | :heavy_multiplication_x: |                                           |

### Checklist ###

- [x] My PR was done against the `dev` branch, not `master`.
- [x] My code follows the code style of this project.
- [x] My change includes a change to the documentation, if required.
- [x] My change adds tests as appropriate.
- [x] I have read and agree to the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by Grazfather** [comment]
Please use the original PR, where the review was done.

**Comment by chkp-eyalit** [comment]
I can't use it because I closed and re-opened the repo in order to be able send it in a different pull request (there was probably a better way, but it was done already). I really am sorry for all of my mess with git, I'm not a developer, I don't work daily with git, and maintainers always tell me to work in a proper "git" way.

What should matter is that I use your project and I think it is great, and I implemented this feature so in August gef won't break on new versions of glibc. The new pull request does fix the comments from the previous review, and I really wonder if the amount of bureaucracy for 17 (tested) lines of code is worth it.

**Comment by hugsy** [comment]
For tracking: this PR was originally from #517

**Comment by Grazfather** [comment]
🤦‍♂ 😅 no big deal

**Comment by hugsy** [comment]
Thanks for the PR @chkp-eyalit!

**Pull request merged**
