### PR TITLE
vmmap: overload argument match address

### PR DESCRIPTION
**Pull request by Mic92**
If you find this feature useful, i will extend the documentation.

### CODE REVIEW

**Comment by Mic92** [comment]
just noticed the overlap with `xinfo`

**Comment by Grazfather** [comment]
We appreciate it anyway!

**Comment by Mic92** [comment]
your choice.

**Comment by Grazfather** [comment]
Could you explain what it does? If it doesn't do anything that xinfo does already, then we don't need it, I just didn't want to discourage you from contributing in the future.

If this is indeed something new I can play with it and see if it's worth inclusion.

**Pull request closed without merging**
