### PR TITLE
Implementation of bincompare command

### PR DESCRIPTION
**Pull request by helviojunior**
### Description/Motivation/Screenshots ###
This patch implement the Bincompare command wich will do the comparason of an Binary file and the memory position in order to find by badchars

### How Has This Been Tested? ###
Yes

### Checklist ###

- [X] My PR was done against the `dev` branch, not `master`.
- [X] My code follows the code style of this project.
- [X] My change includes a change to the documentation, if required.
- [X] My change adds tests as appropriate.
- [X] I have read and agree to the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by daniellimws** [comment]
Thanks for making this! Can you add this to the documentation here too? https://github.com/hugsy/gef/tree/dev/docs

**Comment by helviojunior** [comment]
> Thanks for making this! Can you add this to the documentation here too? https://github.com/hugsy/gef/tree/dev/docs

Yes, i will do that.

BTW, i created another command, Bytearray, do you want that i make another merge request, or everything at this one?

**Comment by daniellimws** [comment]
It would be nicer to make a separate pull request for that.

**Comment by hugsy** [comment]
> Thanks for making this! Can you add this to the documentation here too? 

And unit tests too!

Each new command should be submitted in separate PR, each with squashed commits which include proper documentation to explain what the command does and how to use it and tests added. 

On which architecture/environment was that command tested? The test table of the PR template was just removed and replaced by "yes" which is not helpful for us.

**Comment by helviojunior** [comment]
In order to make the complete Pull request, i will close this one to fill all requirements.

BTW: the Github include all commits toguether.

**Pull request closed without merging**
