### PR TITLE
Fix Color bug

### PR DESCRIPTION
**Pull request by Grazfather**
This PR makes three small changes:

1. Changes the colour lookup from O(n) (`x in list`) to O(1) (`x in dict`)
2. Fixes a small bug where if you underlines AND highlighted, only the highlight would turn off (`elif`)
3. Removes `colors()` method in favor of just using the new `COLORS` class attribute.

### CODE REVIEW

**Comment by hugsy** [comment]
Hey there,

I don't think I will need to merge this PR. I am doing many (many many) changes as I am going through Fluent Python, and `Color` was in it. It will be pushed to `dev` soon, so if you're happy with the changes we can close this PR. Else I will cherry-pick what is missing.

Cheers,

**Comment by Grazfather** [comment]
There are changes in it needed by my other branches. Can you merge and
rebase dev on it? Or will that be too much trouble?

**Comment by Grazfather** [comment]
No need to merge this one, but #116 and #113 should be merged, imo. I'll keep this open just to compare to your new implementation when it's ready.

**Comment by hugsy** [comment]
Agreed, just need time to review them, I woke up 20min ago :coffee: hehe

**Comment by Grazfather** [comment]
Just got my coffee a minute ago :)

**Comment by hugsy** [comment]
Fixed by 385893a046436d5e3aef2bcbf1c044920bf6992c.

**Pull request closed without merging**
